// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'label': string;
  'validation-error': string;
}
export const cssExports: CssExports;
export default cssExports;
