// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'completed': string;
  'modal-content': string;
}
export const cssExports: CssExports;
export default cssExports;
