// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'close-button': string;
  'content': string;
  'footer': string;
  'header': string;
  'header-text': string;
  'styled-modal': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
