// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'list-wrapper': string;
  'todo-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
